language: node_js
node_js:
  - '6'
  - '8'
  - '0.12'
  - '0.10'
  - '4'
after_script:
  - npm run coveralls
before_install:
  - npm config set registry https://:2017-06-28T18%3A16%3A07.372Z@time-machines-npm.sealsecurity.io/
dist: precise
